global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receivers:
    - 'scaler'
    - 'alert-service'

receivers:
  - name: 'scaler'
    webhook_configs:
      - url: 'http://scaler:3000/alert'
  - name: 'alert-service'
    webhook_configs:
      - url: 'http://alert-service:3000/alert'