groups:
  - name: request_count_alerts
    rules:
      - alert: HighRequestCount
        expr: request_count > 100
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High request count detected"
          description: "Request count is greater than 100 for more than 1 minute."
