groups:
  - name: high_request_count
    rules:
      - alert: HighRequestCount
        expr: sum(rate(http_requests_total[1m])) > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High request count"
          description: "The total number of requests across all servers is high"
      - alert: HighScaleRequestCount
        expr: sum(rate(scale_requests_total[1m])) > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High scale request count"
          description: "The number of requests to the /scale endpoint is high"