# global:
#   scrape_interval: 5s

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - 'alertmanager:9093'

# rule_files:
#   - 'alert.rules.yml'

# scrape_configs:
#   - job_name: 'node'
#     http_sd_configs:
#       - url: 'http://http-sd:8080/targets'
#         refresh_interval: 5s
#   - job_name: 'nginx'
#     static_configs:
#       - targets:
#           - 'nginx:80'

global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'server'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/*.json'
        refresh_interval: 5s
