global:
  scrape_interval: 15s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'server1'
    static_configs:
      - targets: ['server1:3001']

  - job_name: 'server2'
    static_configs:
      - targets: ['server2:3002']

  - job_name: 'server3'
    static_configs:
      - targets: ['server3:3003']
